import type { InvoiceDocument } from "../../../shared/types/invoiceDocument";

export function makeInvoiceDocument(overrides: Partial<InvoiceDocument> = {}): InvoiceDocument {
  return {
    id: "doc-1",
    contentHash: "hash-1",
    fileName: "demo.pdf",
    fileSize: 1,
    lastModified: 1,
    handleRef: "",
    bindingStatus: "unreadable",
    bindingErrorType: "handle_missing",
    ocrVendor: null,
    ocrParsedAt: null,
    parseStatus: "parsed",
    conflictStatus: "none",
    conflictMessage: "",
    invoiceNumber: "INV-001",
    invoiceCode: "CODE-1",
    invoiceDate: "2026-04-01",
    totalAmount: 100,
    taxAmount: 10,
    amountWithoutTax: 90,
    buyerName: "Buyer Co",
    sellerName: "Seller Co",
    items: [],
    tags: [],
    remark: "",
    annotation: "",
    uploader: "",
    owner: "",
    collaborationStatus: "local_only",
    reviewStatus: "not_required",
    submittedBy: "",
    receivedBy: "",
    beneficiary: "",
    lastSubmissionId: null,
    sourceType: "ocr",
    edited: false,
    createdAt: "2026-04-01T00:00:00.000Z",
    updatedAt: "2026-04-01T00:00:00.000Z",
    ...overrides,
  };
}
